### ISSUE TITLE
relation to mdx-js/vscode-mdx

### ISSUE THREAD

**Issue by stefanprobst** [silvenon/vscode-mdx#21]
hi, how does this extension relate to this [`vscode-mdx`](https://github.com/mdx-js/vscode-mdx) extension? are both doing essentially the same?

**Comment by silvenon** [comment]
Hey 👋 They were developed completely separately of each other, even though we are both MDX contributors. Mine has many more installs probably in part because it was the first one, so I recommend installing the other one to compare yourself. I haven't done this myself, so feel free to share any insights you get from the comparison here, I would like to know as well. 😄 https://github.com/mdx-js/mdx/discussions/1373#discussioncomment-215294

As you can see by the open issues, I don't maintain mine currently. I might get back to developing it at some point.

**Comment by texastoland** [comment]
Came with the same question. I applaud your friendliness!

**Comment by silvenon** [comment]
Very kind of you!
